### ISSUE TITLE
Add, use and document the jupyterhub's `io_loop` test fixture

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/pytest-jupyterhub#30]
### Proposed change

~Add and document the  [`jupyterhub.conftest.io_loop` fixture](https://github.com/jupyterhub/jupyterhub/blob/95cf06a46e2290ddc5fe9a8b0b2152eebfd2253d/jupyterhub/tests/conftest.py#L133-L143).~

### Update
The amazing information exchange in this issue ( ❤️ ), has helped conclude the following:

- Wirth `pytest-asyncio` usage in jupyterhub's tests, tests can be async and they will be all run on the same event loop, without additional work. Due to this, the explicit use of the [`io_loop` fixture](https://github.com/jupyterhub/jupyterhub/blob/95cf06a46e2290ddc5fe9a8b0b2152eebfd2253d/jupyterhub/tests/conftest.py#L133-L143) in jupyterhub's test suite has almost been removed thanks to https://github.com/jupyterhub/jupyterhub/pull/4332. 

- For the pytest plugin project, the general goal should be to get rid of the `io_loop` fixture completely and don't use it at all. Currently, it is still used in the jupyterhub's test suite to cleanup any remaining open FD between test modules.
The pytest plugin should make sure the MockHub cleanup fully closes and stops everything, so that the extra io_loop teardown doesn't need to happen anymore.

- I believe there is also value in gathering all this information into a small paragraph, maybe inside a README.md file in the `jupyterhub/tests` directory for future readers wanting to learn more about jupyterhub's test suite, in the context of testing asynchronous bits of the app.

Ref https://github.com/jupyterhub/pytest-jupyterhub/pull/28/files#r1090667428

**Comment by Sheila-nk** [comment]
I don't think I have sufficient knowledge of event loops. I will do some research and then tackle this issue so we can implement it in the `app_for_spawners` fixture.

**Comment by GeorgianaElena** [comment]
> I will do some research and then tackle this issue so we can implement it in the app_for_spawners fixture.

@Sheila-nk, yes, asynchronous operations are a complex subject. But yes, please research about this topic a bit, but by paying attention not to get trapped into many rabbit holes. Maybe don't spend more that half a day or a full day on this?
Some possibly useful links:
- Start with this one for context: https://realpython.com/async-io-python/
- https://docs.python.org/3/library/asyncio-eventloop.html
- https://www.pythontutorial.net/python-concurrency/python-event-loop
- https://stackabuse.com/overview-of-async-io-in-python-3-7
- https://www.tornadoweb.org/en/stable/asyncio.html

Hopefully @minrk will be able to help put all this into the `jupyterhub` context.
So my suggestion is to focus on getting a higher level image of the subject and write down questions about the concepts that are unclear. This should help out in setting some healthy grounds before throwing `jupyterhub` in the picture too.

**Comment by consideRatio** [comment]
For me, this is the trickies topic of them all in Python.

I understand it as event loops (where io_loop is an event loop) execute async functions, at least until such functions end up needing to pause to `await` something else. At that time, the event loop will switch to executing another async fuction scheduled for execution and check in again later...

I'm not sure, but I think a co-routine is a function that can be paused and resumed. So that means an async function is a declaration of a co-routine where the event loop running them will pause whenever an `await` statement is detected and what is to be awaited isn't ready.

Yikes, I struggle with clarity still and I've spent so time trying to understand this!

Anyhow, here is one video that I felt made me suddenly understand a few things that I had never understood before:
- A ~20 min video about using multiple threads, using multiple python processes, and Python's "GIL": https://www.youtube.com/watch?v=AZnGRKFUU0c

And searching for videos i've watched, I apparently have watched this as well to the end, so it may be a good overview video:
- A ~20 min video about async/await: https://www.youtube.com/watch?v=bs9tlDFWWdQ

**Comment by Sheila-nk** [comment]
@consideRatio and @GeorgianaElena thank you so much for the resources. Will check back in with a paragraph to test my understanding 😅

**Comment by willingc** [comment]
Hi @Sheila-nk. It's great to see you here. (Hello @GeorgianaElena and @consideRatio too). 

Here's a very good series of videos about asyncio which is Python Standard Library's asynchronous module that implements an event loop: https://www.youtube.com/watch?v=E7Yn5biBZ58

One of the hardest things about event loops and asynchronous programming is all of the jargon around it which increases the complexity. In its simplest form an event loop is a process that handles events/messages that come in to the process. A real world analogy would be a bus which drives around the city. People are getting on and off at different times. Think of the bus (event loop) as the way people (events) get rides around the city. People hop on and off the bus when they start their ride and when they finish their ride. While they are on the bus, the people are idle waiting for their next stop. 

The event loop is a way of serving lots of events/messages that happen at different times. By sharing the event loop process, a system can handle many events. The io_loop is basically a special type of an event loop that handle the input and output of messages/events.

**Comment by Sheila-nk** [comment]
Hey, @willingc 👋 thanks for taking the time to provide resources and an overview of event loops. The bus analogy is really helpful.

**Comment by minrk** [comment]
Thanks, @willingc!

The most important and challenging part of event loops in testing is that you need to make sure to use the _same one_ throughout a given test or collection of tests. In JupyterHub, we use tornado, which is a wrapper around asyncio's event loop. It's unlikely that the tornado io_loop will be needed _directly_ in tests. It's very important that the tornado io loop is 'hooked up to' the main asyncio event loop, otherwise you'll get mysterious hangs, as events you are waiting for just never happen because they are hooked up to an event loop that's not running.

We use `pytest-asyncio`, which means we can write any tests with `async def`, and they will be run appropriately with an event loop.

Another important aspect to consider with fixtures is [scope](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session). It is _simplest_ for fixtures and everything to have a 'function' scope (this is the default), meaning they are called (and cleaned up) separately for every single test function. However, in JupyterHub itself for performance reasons, we only instantiate a JupyterHub Application object [once per test file or _module_](https://github.com/jupyterhub/jupyterhub/blob/3.1.1/jupyterhub/tests/conftest.py#L60). This is not required, but it saves us having to launch and shutdown a whole JupyterHub app for every test, which is slow. But because the application itself _uses_ the event loop and io_loop fixtures, those fixtures, too, must also have a scope as long or longer.

Key points:

- pytest-asyncio defines an `event_loop` fixture, and uses that loop to run any test or fixture is async (starts with `async def`)
- we only need to override the `event_loop` fixture if we want to change its _scope_ to something other than the default `function`, which in turn we only need to do if another fixture _using_ the event loop wants to have a longer scope (e.g. `app` - maybe not for this project!)
- tornado's io_loop should be connected to the event loop. The simplest way to do this is to use [`async def`](https://github.com/jupyterhub/jupyterhub/blob/3.1.1/jupyterhub/tests/conftest.py#L133) for the io_loop fixture itself. In fact, we may not really need the `io_loop` fixture at all, with the current state of pytest-asyncio. I'm investigating this now.
